/* 1) Find each customer’s first order that was NOT cancelled and NOT returned
   2) Determine which product category appears in the largest number of those first orders
   3) Calculate total revenue (sale_price) generated by that category across all
      NON-cancelled / NON-returned order-items. */
WITH first_good_orders AS (
    SELECT
        "user_id",
        MIN("created_at") AS "first_created_at"
    FROM THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."ORDERS"
    WHERE "status" <> 'Cancelled'
      AND "returned_at" IS NULL
    GROUP BY "user_id"
),

first_order_categories AS (
    SELECT
        o."user_id",
        p."category"
    FROM THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."ORDERS"        o
    JOIN first_good_orders                                   f
      ON  o."user_id"     = f."user_id"
     AND o."created_at"   = f."first_created_at"
    JOIN THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."ORDER_ITEMS"   oi
      ON oi."order_id"    = o."order_id"
    JOIN THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."PRODUCTS"      p
      ON p."id"           = oi."product_id"
),

top_category AS (
    SELECT "category"
    FROM   first_order_categories
    GROUP  BY "category"
    ORDER  BY COUNT(DISTINCT "user_id") DESC NULLS LAST
    LIMIT  1
),

category_revenue AS (
    SELECT
        SUM(oi."sale_price") AS "total_revenue"
    FROM THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."ORDER_ITEMS"   oi
    JOIN THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."ORDERS"        o
      ON oi."order_id" = o."order_id"
    JOIN THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."PRODUCTS"      p
      ON p."id"        = oi."product_id"
    JOIN top_category                                         tc
      ON tc."category" = p."category"
    WHERE o."status"         <> 'Cancelled'
      AND o."returned_at"     IS NULL
      AND oi."status"        <> 'Cancelled'
      AND oi."returned_at"    IS NULL
)

SELECT
    tc."category",
    cr."total_revenue"
FROM   top_category     tc
CROSS  JOIN category_revenue cr;