/*---------------------------------------------------------
   Two–week retention (14-day) for every “quickplay” event
   – Cohort: users who triggered a session_start between
     2-Jul-2018 and 16-Jul-2018 (inclusive)
---------------------------------------------------------*/

WITH union_events AS (      -- 2-Jul-2018 … 30-Jul-2018
    SELECT "event_date","event_name","user_pseudo_id"
      FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180702"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180703"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180704"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180705"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180706"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180707"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180708"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180709"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180710"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180711"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180712"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180713"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180714"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180715"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180716"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180717"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180718"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180719"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180720"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180721"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180722"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180723"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180724"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180725"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180726"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180727"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180728"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180729"
    UNION ALL SELECT "event_date","event_name","user_pseudo_id" FROM FIREBASE.ANALYTICS_153293282."EVENTS_20180730"
),

/*---------------------------------------------------------
   Users that opened a session during the cohort window
---------------------------------------------------------*/
cohort_users AS (
    SELECT DISTINCT "user_pseudo_id"
      FROM union_events
     WHERE "event_name" = 'session_start'
       AND "event_date" BETWEEN '20180702' AND '20180716'
),

/*---------------------------------------------------------
   Quick-play events generated by the cohort in that window
---------------------------------------------------------*/
quickplay_events AS (
    SELECT  ue."user_pseudo_id",
            ue."event_name"                                AS quickplay_type,
            TO_DATE(ue."event_date",'YYYYMMDD')            AS event_dt
      FROM union_events ue
      JOIN cohort_users cu
        ON cu."user_pseudo_id" = ue."user_pseudo_id"
     WHERE ue."event_name" ILIKE '%quickplay%'
       AND ue."event_date" BETWEEN '20180702' AND '20180716'
),

/*---------------------------------------------------------
   First (initial) quick-play event for every user & type
---------------------------------------------------------*/
initial_quickplay AS (
    SELECT  "user_pseudo_id",
            quickplay_type,
            MIN(event_dt) AS initial_dt
      FROM quickplay_events
     GROUP BY "user_pseudo_id", quickplay_type
),

/*---------------------------------------------------------
   Was the user active exactly 14 days later?
---------------------------------------------------------*/
retention_flag AS (
    SELECT  iq.quickplay_type,
            iq."user_pseudo_id",
            CASE
                WHEN EXISTS (
                    SELECT 1
                      FROM union_events u2
                     WHERE u2."user_pseudo_id" = iq."user_pseudo_id"
                       AND TO_DATE(u2."event_date",'YYYYMMDD')
                           = DATEADD(day,14,iq.initial_dt)
                )
                THEN 1 ELSE 0
            END AS retained
      FROM initial_quickplay iq
)

/*---------------------------------------------------------
   Final 14-day retention rate per quick-play event type
---------------------------------------------------------*/
SELECT  quickplay_type                             AS "quickplay_event",
        COUNT(*)                                   AS "cohort_users",
        SUM(retained)                              AS "retained_users",
        ROUND( CAST(SUM(retained) AS FLOAT) 
               / COUNT(*) * 100 , 4)               AS "retention_rate_percent"
  FROM retention_flag
 GROUP BY quickplay_type
 ORDER BY "retention_rate_percent" DESC NULLS LAST;