-- Total daily page-views in Nov-2020 and the average per purchaser
WITH purchasers AS (   -- users who bought at least once in Nov-2020
  SELECT DISTINCT user_pseudo_id
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_202011*`
  WHERE event_name = 'purchase'
),
daily AS (             -- page-views generated by those purchasers
  SELECT
    event_date,
    COUNT(*)                         AS page_views,
    COUNT(DISTINCT user_pseudo_id)   AS users
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_202011*`
  WHERE event_name = 'page_view'
    AND user_pseudo_id IN (SELECT user_pseudo_id FROM purchasers)
  GROUP BY event_date
)
SELECT
  PARSE_DATE('%Y%m%d', event_date)         AS date,
  page_views,
  users,
  SAFE_DIVIDE(page_views, users)           AS avg_page_views_per_user
FROM daily
ORDER BY date;