WITH film_revenue AS (
    /* 1.  Total revenue generated by each film */
    SELECT  i.film_id,
            SUM(p.amount) AS total_revenue
    FROM    payment  p
    JOIN    rental   r ON r.rental_id   = p.rental_id
    JOIN    inventory i ON i.inventory_id = r.inventory_id
    GROUP BY i.film_id
),
actor_count AS (
    /* 2.  How many actors acted in each film */
    SELECT  film_id,
            COUNT(*) AS num_actors
    FROM    film_actor
    GROUP BY film_id
),
film_revenue_per_actor AS (
    /* 3.  Split the film revenue equally among its actors */
    SELECT  fr.film_id,
            fr.total_revenue,
            ac.num_actors,
            fr.total_revenue * 1.0 / ac.num_actors AS revenue_per_actor
    FROM    film_revenue fr
    JOIN    actor_count  ac ON ac.film_id = fr.film_id
),
actor_film_revenue AS (
    /* 4.  Attach every actor to his/her share of each film’s revenue */
    SELECT  fa.actor_id,
            a.first_name,
            a.last_name,
            fa.film_id,
            f.title,
            frpa.revenue_per_actor
    FROM    film_actor            fa
    JOIN    actor                 a   ON a.actor_id  = fa.actor_id
    JOIN    film_revenue_per_actor frpa ON frpa.film_id = fa.film_id
    JOIN    film                  f   ON f.film_id   = fa.film_id
),
ranked AS (
    /* 5.  Rank films by an actor’s revenue share, highest first */
    SELECT  *,
            ROW_NUMBER() OVER (PARTITION BY actor_id
                               ORDER BY revenue_per_actor DESC, film_id) AS rn
    FROM    actor_film_revenue
),
top3 AS (
    /* 6.  Keep only the top‑three revenue‑generating films per actor */
    SELECT *
    FROM   ranked
    WHERE  rn <= 3
)
SELECT  actor_id,
        first_name,
        last_name,
        film_id,
        title  AS film_title,
        ROUND(revenue_per_actor, 4)           AS revenue_per_actor,
        ROUND(AVG(revenue_per_actor) OVER
              (PARTITION BY actor_id), 4)     AS avg_top3_revenue_per_actor
FROM    top3
ORDER BY actor_id,
         revenue_per_actor DESC,
         film_id;