WITH film_revenue AS (
    /* Total revenue generated by each film               */
    SELECT  f.film_id,
            SUM(p.amount)                  AS film_revenue
    FROM    film      AS f
    JOIN    inventory AS i   USING (film_id)
    JOIN    rental    AS r   USING (inventory_id)
    JOIN    payment   AS p   USING (rental_id)
    GROUP BY f.film_id
),
actor_per_film AS (
    /* How many actors acted in every film                */
    SELECT  film_id,
            COUNT(DISTINCT actor_id)        AS actor_cnt
    FROM    film_actor
    GROUP BY film_id
),
film_metrics AS (
    /* Film revenue split equally among its actors        */
    SELECT  fr.film_id,
            fr.film_revenue,
            ap.actor_cnt,
            fr.film_revenue * 1.0 / ap.actor_cnt  AS per_actor_revenue
    FROM    film_revenue fr
    JOIN    actor_per_film ap USING (film_id)
),
actor_film AS (
    /* Attach every actor to his/her share of each film   */
    SELECT  fa.actor_id,
            fm.film_id,
            fm.film_revenue,
            fm.per_actor_revenue
    FROM    film_actor  fa
    JOIN    film_metrics fm  ON fm.film_id = fa.film_id
),
ranked AS (
    /* Rank films per actor by the revenue share          */
    SELECT  af.*,
            ROW_NUMBER() OVER (PARTITION BY actor_id
                               ORDER BY per_actor_revenue DESC, film_id ASC) AS rn
    FROM    actor_film af
),
top3 AS (
    /* Keep only the top‑three films for every actor      */
    SELECT *
    FROM   ranked
    WHERE  rn <= 3
),
avg_top3 AS (
    /* Average of the revenue shares of those top three   */
    SELECT actor_id,
           AVG(per_actor_revenue) AS avg_top3_revenue
    FROM   top3
    GROUP BY actor_id
)
SELECT  a.actor_id,
        a.first_name,
        a.last_name,
        t.film_id,
        f.title                       AS film_title,
        ROUND(t.film_revenue       ,4) AS film_revenue,
        ROUND(t.per_actor_revenue  ,4) AS per_actor_revenue,
        ROUND(at.avg_top3_revenue  ,4) AS actor_avg_top3_revenue
FROM    top3        AS t
JOIN    actor       AS a  ON a.actor_id = t.actor_id
JOIN    film        AS f  ON f.film_id  = t.film_id
JOIN    avg_top3    AS at ON at.actor_id = t.actor_id
ORDER BY a.actor_id,
         t.per_actor_revenue DESC,
         t.film_id;