/* 7–day retention for users whose very first session_start
   happened during the Monday‑based week that starts 2018‑07‑02       */

WITH
/* 1. All session_start events that can take part in the analysis    */
session_starts AS (
  SELECT
    user_pseudo_id,
    PARSE_DATE('%Y%m%d', event_date) AS event_date
  FROM `firebase-public-project.analytics_153293282.events_*`
  WHERE _TABLE_SUFFIX BETWEEN '20180702' AND '20181002'        -- only data up to 2‑Oct‑2018
    AND event_name = 'session_start'
),

/* 2. First‑ever session date for every user                         */
first_session AS (
  SELECT
    user_pseudo_id,
    MIN(event_date) AS first_session_date
  FROM session_starts
  GROUP BY user_pseudo_id
),

/* 3. Cohort = users whose first session fell in week starting 2‑Jul */
cohort AS (
  SELECT
    user_pseudo_id
  FROM first_session
  WHERE first_session_date BETWEEN DATE '2018-07-02' AND DATE '2018-07-08'   -- Mon‑Sun
),

/* 4. All later session_start events generated by those cohort users */
cohort_sessions AS (
  SELECT
    s.user_pseudo_id,
    s.event_date
  FROM session_starts AS s
  JOIN cohort        AS c
    ON s.user_pseudo_id = c.user_pseudo_id
  WHERE s.event_date <= DATE '2018-10-02'
),

/* 5. Map every session to a week index relative to 2018‑07‑02       */
weekly_sessions AS (
  SELECT
    user_pseudo_id,
    DIV(DATE_DIFF(event_date, DATE '2018-07-02', DAY), 7) AS week_number
  FROM cohort_sessions
  WHERE event_date <= DATE '2018-08-05'  -- Week 4 ends 5‑Aug‑2018
),

/* 6. Retained users in weeks 1‑4 (distinct users per week)          */
retained AS (
  SELECT
    week_number,
    COUNT(DISTINCT user_pseudo_id) AS users
  FROM weekly_sessions
  WHERE week_number BETWEEN 1 AND 4
  GROUP BY week_number
)

/* 7. Combine Week 0 new‑user count with Week 1‑4 retention          */
SELECT *
FROM (
  SELECT 0 AS week_number, COUNT(*) AS users   -- Week 0 : size of cohort
  FROM cohort
  UNION ALL
  SELECT week_number, users
  FROM retained
)
ORDER BY week_number;