/*--------------------------------------------------------------------
  1. Identify each shopper’s first successful order
     (i.e., not cancelled and not returned).
  2. Determine which product category appears in the greatest
     number of those first‑time orders.
  3. Return the total revenue (sale_price) generated by that
     top category across ALL successful order items.
--------------------------------------------------------------------*/
WITH first_successful_orders AS (          -- step‑1
    SELECT  o."user_id",
            MIN(o."created_at") AS first_created_at
    FROM    THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."ORDERS" o
    WHERE   o."status" <> 'Cancelled'
      AND   o."returned_at" IS NULL
    GROUP BY o."user_id"
),

first_order_ids AS (                      -- map users to the real order_id(s)
    SELECT  o."user_id",
            o."order_id"
    FROM    THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."ORDERS" o
    JOIN    first_successful_orders f
           ON f."user_id" = o."user_id"
          AND f.first_created_at = o."created_at"
    WHERE   o."status" <> 'Cancelled'
      AND   o."returned_at" IS NULL
),

category_customer_counts AS (             -- step‑2
    SELECT  p."category",
            COUNT(DISTINCT f."user_id") AS customer_cnt
    FROM    first_order_ids f
    JOIN    THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."ORDER_ITEMS" oi
           ON oi."order_id" = f."order_id"
    JOIN    THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."PRODUCTS" p
           ON p."id" = oi."product_id"
    WHERE   oi."status" <> 'Cancelled'
      AND   oi."returned_at" IS NULL
    GROUP BY p."category"
),

top_category AS (                         -- pick the category with most customers
    SELECT  "category"
    FROM    (
              SELECT  ccc."category",
                      ccc.customer_cnt,
                      ROW_NUMBER() OVER (ORDER BY ccc.customer_cnt DESC) AS rn
              FROM    category_customer_counts ccc
            )
    QUALIFY rn = 1
),

category_revenue AS (                     -- step‑3
    SELECT  SUM(oi."sale_price") AS revenue
    FROM    THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."ORDER_ITEMS" oi
    JOIN    THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."PRODUCTS" p
           ON p."id" = oi."product_id"
    JOIN    top_category tc
           ON p."category" = tc."category"
    WHERE   oi."status" <> 'Cancelled'
      AND   oi."returned_at" IS NULL
)

-- Final result
SELECT  tc."category"     AS top_category,
        cr.revenue        AS total_revenue
FROM    top_category   tc
CROSS JOIN category_revenue cr;