-- Weekly retention for users whose very first `first_open`
-- happened within 2018‑09‑01 ~ 2018‑09‑07 (Asia/Shanghai time)

WITH base_events AS (
  SELECT
    user_pseudo_id,
    event_name,
    TIMESTAMP_MICROS(event_timestamp)                            AS event_ts_utc,
    DATETIME(TIMESTAMP_MICROS(event_timestamp), 'Asia/Shanghai') AS event_dt_sh
  FROM `firebase-public-project.analytics_153293282.events_*`
  -- grab every event we may need: 8 h of 20180831 (UTC) up to 20180928
  WHERE _TABLE_SUFFIX BETWEEN '20180831' AND '20180928'
),

/* cohort = users whose first `first_open` fell in the
   first Shanghai week of September 2018 */
cohort AS (
  SELECT
    user_pseudo_id,
    MIN(event_ts_utc) AS first_open_ts_utc,
    MIN(event_dt_sh)  AS first_open_dt_sh          -- keeps Shanghai TZ
  FROM base_events
  WHERE event_name = 'first_open'
    AND event_dt_sh >= DATETIME '2018-09-01'
    AND event_dt_sh <  DATETIME '2018-09-08'       -- up‑to‑but‑not‑incl. 2018‑09‑08
  GROUP BY user_pseudo_id
),

/* any subsequent event generated by a cohort user within
   21 days after the first_open (Shanghai time) */
returns AS (
  SELECT DISTINCT
    c.user_pseudo_id,
    CASE
      WHEN day_diff BETWEEN  1 AND  7 THEN 1
      WHEN day_diff BETWEEN  8 AND 14 THEN 2
      WHEN day_diff BETWEEN 15 AND 21 THEN 3
    END AS week_no
  FROM base_events        AS e
  JOIN cohort             AS c USING (user_pseudo_id)
  CROSS JOIN UNNEST([
    DATE_DIFF(DATE(e.event_dt_sh), DATE(c.first_open_dt_sh), DAY)
  ]) AS day_diff
  WHERE day_diff BETWEEN 1 AND 21                     -- ignore day‑0
),

week_counts AS (
  SELECT
    week_no,
    COUNT(DISTINCT user_pseudo_id) AS retained_users
  FROM returns
  GROUP BY week_no
),

cohort_size AS (SELECT COUNT(*) AS n FROM cohort)

/* final retention percentages (0‑4 decimal places kept) */
SELECT
  ROUND(100 * SAFE_DIVIDE(MAX(IF(week_no = 1, retained_users, NULL)),
                          (SELECT n FROM cohort_size)), 4) AS week1_retention_rate,
  ROUND(100 * SAFE_DIVIDE(MAX(IF(week_no = 2, retained_users, NULL)),
                          (SELECT n FROM cohort_size)), 4) AS week2_retention_rate,
  ROUND(100 * SAFE_DIVIDE(MAX(IF(week_no = 3, retained_users, NULL)),
                          (SELECT n FROM cohort_size)), 4) AS week3_retention_rate
FROM week_counts;