-- Total page views per day in Nov‑2020 and average page views per purchasing user
WITH purchase_users AS (
  -- Users who made at least one purchase in November 2020
  SELECT DISTINCT user_pseudo_id
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_202011*`
  WHERE event_name = 'purchase'
),
page_views AS (
  -- Page‑view events in November 2020 generated by those users
  SELECT
    PARSE_DATE('%Y%m%d', event_date) AS event_date,
    user_pseudo_id
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_202011*`
  WHERE event_name = 'page_view'
    AND user_pseudo_id IN (SELECT user_pseudo_id FROM purchase_users)
)
SELECT
  event_date,
  COUNT(*) AS total_page_views,
  COUNT(DISTINCT user_pseudo_id) AS users_with_page_view,
  SAFE_DIVIDE(COUNT(*), COUNT(DISTINCT user_pseudo_id)) AS avg_page_views_per_user
FROM page_views
GROUP BY event_date
ORDER BY event_date;