from deepscaler.rewards.evaluate import evaluate_spider2sql
import os

ground_truths = "deepscaler/rewards/gold/gold_answer"
model_answer = "-- Task: From the CITY_LEGISLATION.CITY_LEGISLATION.CITIES table, identify the country (by \"country_code_2\") that has data entries on exactly nine distinct days in January 2022 (based on \"insert_date\"). Then, for this country, find the longest consecutive sequence of dates in January 2022 with data entries. Calculate the total number of entries and the number of entries from the capital city (where \"capital\" = 1) during this period, and compute the proportion of entries from the capital city among all entries in this period.\nWITH country_with_nine_insertion_days AS (\n    SELECT \"country_code_2\"\n    FROM (\n        SELECT \"country_code_2\", COUNT(DISTINCT \"insert_date\") AS insertion_days\n        FROM CITY_LEGISLATION.CITY_LEGISLATION.CITIES\n        WHERE \"insert_date\" LIKE '2022-01-%'\n        GROUP BY \"country_code_2\"\n    )\n    WHERE insertion_days = 9\n    LIMIT 1\n),\ncapital_city AS (\n    SELECT \"city_name\"\n    FROM CITY_LEGISLATION.CITY_LEGISLATION.CITIES\n    WHERE \"country_code_2\" = (SELECT \"country_code_2\" FROM country_with_nine_insertion_days)\n      AND \"capital\" = 1\n    LIMIT 1\n),\ncountry_inserts AS (\n    SELECT \n        TO_DATE(\"insert_date\", 'YYYY-MM-DD') AS \"insert_date\",\n        \"city_name\",\n        CASE WHEN \"city_name\" = (SELECT \"city_name\" FROM capital_city) THEN 1 ELSE 0 END AS is_capital\n    FROM CITY_LEGISLATION.CITY_LEGISLATION.CITIES\n    WHERE \"insert_date\" LIKE '2022-01-%' \n      AND \"country_code_2\" = (SELECT \"country_code_2\" FROM country_with_nine_insertion_days)\n),\ncountry_dates AS (\n    SELECT DISTINCT \"insert_date\"\n    FROM country_inserts\n),\nordered_dates AS (\n    SELECT \n        \"insert_date\",\n        ROW_NUMBER() OVER (ORDER BY \"insert_date\") AS rn\n    FROM country_dates\n),\ngrouped_dates AS (\n    SELECT \n        \"insert_date\",\n        DATEADD(DAY, -rn, \"insert_date\") AS grp\n    FROM ordered_dates\n),\nconsecutive_periods AS (\n    SELECT \n        grp,\n        MIN(\"insert_date\") AS start_date,\n        MAX(\"insert_date\") AS end_date,\n        COUNT(*) AS consecutive_days\n    FROM grouped_dates\n    GROUP BY grp\n    ORDER BY consecutive_days DESC NULLS LAST\n    LIMIT 1\n),\ncounts AS (\n    SELECT\n        COUNT(*) AS total_entries,\n        SUM(is_capital) AS capital_entries\n    FROM country_inserts\n    WHERE \"insert_date\" BETWEEN (SELECT start_date FROM consecutive_periods) AND (SELECT end_date FROM consecutive_periods)\n)\nSELECT\n    TO_CHAR((SELECT start_date FROM consecutive_periods), 'YYYY-MM-DD') AS START_DATE,\n    TO_CHAR((SELECT end_date FROM consecutive_periods), 'YYYY-MM-DD') AS END_DATE,\n    (SELECT consecutive_days FROM consecutive_periods) AS CONSECUTIVE_DAYS,\n    counts.total_entries AS TOTAL_ENTRIES,\n    counts.capital_entries AS CAPITAL_ENTRIES,\n    ROUND(counts.capital_entries / counts.total_entries::FLOAT, 4) AS PROPORTION_CAPITAL_ENTRIES\nFROM counts;"
sqlite_path = None
example_id = "sf_local072_aug0"
csv_save_path = os.path.join("exec", example_id+".csv")

# if execute_sql_api(model_answer, csv_save_path, api=get_api_name(example_id), sqlite_path=sqlite_path) == 0:
is_correct = evaluate_spider2sql(ground_truths, "exec/bq230.csv", "bq230")
print(is_correct)