-- 7-day (Monday-based) retention for the cohort whose first-ever session occurred
-- during the week that started on Monday 2-Jul-2018 (Week 0).
-- Results: Week 0 cohort size and number of retained users for Weeks 0-4.
WITH first_sessions AS (      -- first calendar day each user ever started a session
  SELECT
    user_pseudo_id,
    MIN(PARSE_DATE('%Y%m%d', event_date)) AS first_session_date
  FROM `firebase-public-project.analytics_153293282.events_*`
  WHERE event_name = 'session_start'
    AND _TABLE_SUFFIX BETWEEN '20180612' AND '20181002'   -- reasonable look-back window
  GROUP BY user_pseudo_id
),
cohort AS (                   -- users whose very first session fell in Week 0
  SELECT user_pseudo_id
  FROM first_sessions
  WHERE first_session_date BETWEEN DATE '2018-07-02' AND DATE '2018-07-08'
),
events_in_scope AS (          -- all events generated by those cohort users
  SELECT
    user_pseudo_id,
    PARSE_DATE('%Y%m%d', event_date) AS event_date
  FROM `firebase-public-project.analytics_153293282.events_*`
  WHERE _TABLE_SUFFIX BETWEEN '20180702' AND '20181002'   -- ignore anything after 2-Oct-2018
    AND user_pseudo_id IN (SELECT user_pseudo_id FROM cohort)
),
retention AS (                -- map every event to its Monday-based week number
  SELECT
    DIV(DATE_DIFF(event_date, DATE '2018-07-02', DAY), 7) AS week_number,  -- 0 = Week 0
    COUNT(DISTINCT user_pseudo_id)                  AS retained_users
  FROM events_in_scope
  WHERE event_date <= DATE '2018-10-02'
  GROUP BY week_number
  HAVING week_number BETWEEN 0 AND 4                -- only Weeks 0-4
),
cohort_size AS (              -- Week 0 new-user count (cohort size)
  SELECT COUNT(*) AS week0_users FROM cohort
)
SELECT
  r.week_number,
  c.week0_users,
  r.retained_users
FROM retention AS r
CROSS JOIN cohort_size AS c
ORDER BY r.week_number;